### ISSUE TITLE
Update README.md with new demo

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/git-stalk-cli#12]

**Comment by NefixEstrada** [comment]
Could you elaborate a bit more, please?

**Comment by NefixEstrada** [comment]
Could you elaborate a bit more, please?

**Comment by aashutoshrathi** [comment]
Current README has a demo output, but after that many new features like org filter have been implemented.
Try adding a GIF for that.

**Comment by NefixEstrada** [comment]
Sure
