### ISSUE TITLE
Integrate auto linting during Travis Build

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/git-stalk-cli#20]

**Comment by StegSchreck** [comment]
Hey @aashutoshrathi.
I made the necessary changes for linting in https://github.com/aashutoshrathi/git-stalk-cli/pull/26

You can still adjust it by using a `.pylintrc` file.

**Comment by amcintosh** [comment]
You could also consider wiring up Stickler: https://stickler-ci.com/
