### ISSUE TITLE
Handle error

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/git-stalk-cli#35]
```sh
star_table.add_row([starred_repo.name, starred_repo.language, starred_repo.time])
AttributeError: 'dict' object has no attribute 'name'
```

**Comment by Galixxon** [comment]
How could I test changes done by me?

**Comment by aashutoshrathi** [comment]
Run the python file locally with one since argument

**Comment by Galixxon** [comment]
I can't see where the problem lies. I'm running stalk.py without any errors. (using my username and few random ones for testing)

**Comment by aashutoshrathi** [comment]
Try adding --since or --while arguements
