### ISSUE TITLE
Add new flags

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/git-stalk-cli#46]
Add new flags like Follows and Following.

**Comment by nikhilbhatewara** [comment]
Can you give some more details on this?

**Comment by aashutoshrathi** [comment]
`stalk <username> --followers`
Should return Followers of user.

**Comment by ammarmallik** [comment]
I can work on this if @nikhilbhatewara hasn't started this yet.

**Comment by aashutoshrathi** [comment]
Sure take it @ammarmallik

**Comment by VANKINEENITAWRUN** [comment]
@aashutoshrathi I have done it with followers and follows both flags can check the PR.

**Comment by aashutoshrathi** [comment]
Sure checking.
