### ISSUE TITLE
Fix function too complex

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/git-stalk-cli#49]
Functions have too much complexity, they are needed to be resolved.
Refrences: https://lintlyci.github.io/Flake8Rules/rules/C901.html

Log:
```sh
/home/travis/build/aashutoshrathi/git-stalk-cli/git_stalk/stalk.py:34: C901 'get_details' is too complex (10)
/home/travis/build/aashutoshrathi/git-stalk-cli/git_stalk/stalk.py:232: C901 'filter_since_until_dates' is too complex (10)
/home/travis/build/aashutoshrathi/git-stalk-cli/git_stalk/stalk.py:259: C901 'show_contri' is too complex (11)
```

**Comment by pratik97** [comment]
I would like to work on this issue.

**Comment by pratik97** [comment]
Sorry, I won't be working on this. Will leave it for someone else.

**Comment by dreuse** [comment]
Hi, @aashutoshrathi  I'd like to take a look at this if it's not really urgent.

**Comment by aashutoshrathi** [comment]
Sure send a PR, if your PR solves this, I'll merge
