### ISSUE TITLE
Fix KeyError

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/git-stalk-cli#62]
We are getting KeyError for Issue and Name.

**Comment by santiago177** [comment]
Is this the error?
![captura](https://user-images.githubusercontent.com/13248292/47400728-195a7600-d704-11e8-9a36-1dc51eeee700.PNG)

**Comment by MishaLarionov** [comment]
Addressed in my pull request. Looking at the code I would also suggest updating the entire codebase to PEP8, as using comments beginning with `#` would be preferable to string comments.

**Comment by VANKINEENITAWRUN** [comment]
event["payload"] JSON have the key as the issue only in few payloads. it's because of it. should the API be changed or the implementation?.
I am Interested in doing it.

**Comment by aashutoshrathi** [comment]
@VANKINEENITAWRUN Try resolving it, I'll check the PR

**Comment by Grokzen** [comment]
When running `stalk Grokzen` you get the following stack trace back. It do not cause this on every user, but currently on mine.

```
Contributions Today:                                                                            
Traceback (most recent call last):                                                      
  File "/home/grok/.virtualenvs/git-stalk/bin/stalk", line 11, in <module>
    load_entry_point('git-stalk', 'console_scripts', 'stalk')()                         
  File "/home/grok/code/github/git-stalk-cli/git_stalk/stalk.py", line 428, in run
    show_contri(args)
  File "/home/grok/code/github/git-stalk-cli/git_stalk/stalk.py", line 391, in show_contri
    get_contributions(user, latest, text_date)
  File "/home/grok/code/github/git-stalk-cli/git_stalk/stalk.py", line 206, in get_contributions
    get_details(event),
  File "/home/grok/code/github/git-stalk-cli/git_stalk/stalk.py", line 73, in get_details
    "IssuesEvent": event["payload"]["issue"]["title"],                    
KeyError: 'issue'                                              
```

**Comment by aashutoshrathi** [comment]
@Grokzen happened same with me

**Comment by VANKINEENITAWRUN** [comment]
@aashutoshrathi @Grokzen it happens with many users. The JSON that GitHub API sends doesn't have all the fields always. I tried adding KEY ERROR try catch in every line then it worked but Travis tests fail for the function being too complex.
![screenshot from 2018-10-30 14-12-38](https://user-images.githubusercontent.com/30470229/47706002-21f40480-dc4e-11e8-9b45-c5dd58c6f666.png)

**Comment by aashutoshrathi** [comment]
No worries, we will fix the Travis later, lets fix this first
