### ISSUE TITLE
Running without any arguments should show help

### ISSUE THREAD

**Issue by Grokzen** [aashutoshrathi/git-stalk-cli#64]
When i run the following
```
(git-stalk) ➜  git-stalk git:(master) ✗ stalk
User with username None does not exists, please check and try again
```
I would expect a help message same as running `stalk --help` and not that it would default to trying to query the None user as that user would never exist or make sense to query the server for.

**Comment by aashutoshrathi** [comment]
Yeah sure, would you like to work on it?

**Comment by Grokzen** [comment]
I am no argparse ninja, but don't look that difficult to solve. Have you considered using docopt for cli parsing instead of argparse? Downside is one more dependency, upside is simpler cli handling for simpler cli tools.

**Comment by aashutoshrathi** [comment]
As long as it works, I have nothing against docopt either. :sweat_smile:

**Comment by VANKINEENITAWRUN** [comment]
I would like to work on it

**Comment by aashutoshrathi** [comment]
Sure take it

**Comment by Grokzen** [comment]
@VANKINEENITAWRUN go ahead. Please link this issue in your MR when submited.

**Comment by VANKINEENITAWRUN** [comment]
@Grokzen can you please tell what MR is?

**Comment by aashutoshrathi** [comment]
I think this is solved in https://github.com/aashutoshrathi/git-stalk-cli/commit/e2676bd1563339bb968ddd64590edd39892ae63b

**Comment by Grokzen** [comment]
@VANKINEENITAWRUN sorry, i am used to gitlab and other csv systems where they use Merge Request and not Pull Request like they do here on github. Can't get it out of my muscle memory :)
